### ISSUE TITLE
Making slabs from planks

### ISSUE THREAD

**Issue by Knigge** [Bunsan/TechNodeFirmaCraft#70]
Thanks for fixing more of the issues, even when the pack is dormant. I'm listing a few issues in the chance that you some time later will want to fix even more:)

NEI shows that you are able to craft slabs for various wood planks with a TFC saw, yet when attempting you get no output. Could you either remove this, or make it possible?

**Comment by Bunsan** [comment]
It works for me in SSP. Could you please test in SSP an verify that your scripts in client and server are the same.

**Comment by Knigge** [comment]
In SSP I can craft Maple Wood Slabs 192:22 from for instance Maple Wood Planks 191:22, but these are not obtainable from the regular maple. 

For instance will pine logs that are from trees spawned in the world initially yield Pine Planks 587:8, and all similar kinds of Plank can not be crafted into slabs.

As I understand it, the forestry trees can be used to make slabs, yet the tnfc edited ones can not. Information per tooltip.

**Comment by Bunsan** [comment]
I'm sorry I really do not understand what you are saying. First number IDs aren't useful as they are not constant. The IDs are things like Forestry:Planks:20. The maple planks and slabs you are referencing I think are from forestry, which work in SSP and SMP?

Are you saying that you can not craft planks obtained from TFC trees that you get in worldgen into slab? If so that is intended. Like stairs there are no slab blocks; you need to use the chisel to make them into stairs in world. Even if I wanted to there are no slab blocks to add into a crafting recipe. The only reason you can craft forestry trees into slabs in crafting grid is that there is no way to make them work with chisel for in world crafting.

Are you saying that the planks from forestry trees in the pack can be made into slabs with the saw by crafting? Is this SSP, SMP or both, because they all work for me.

**Comment by Knigge** [comment]
Its new to me that the numbers for an item is not constant, they seem to be for me between instances.

TFC logs obtained through cutting them in the world can not yield stairs. This seems weird to a player that don't know the history behind this.

**Comment by Bunsan** [comment]
There is nothing I can do about this. There are no stair blocks. There are only chiseled blocks skinned to the blocks texture. That is just how TFC works and it is a TFC based pack.
